default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.9
      args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "./scripts/run-mypy.sh"
        language: python
        language_version: python3.10
        additional_dependencies: ["mypy==0.991"]
        types: [python]
        require_serial: true
        verbose: true
